branches: [ "main", "neuer-branch-name" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri application
      env:
        PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1
      run: npm run tauri build